# Should Villager functionality be enabled?
villager: true
# Should Zombie villager functionality be enabled?
zombie-villager: true
# Should Wandering Trader functionality be enabled?
wandering-trader: true

# Disables players placing villager buckets of types that have been disabled if they obtain one somehow
disable-bucket-use-on-disable: false

# Should a players reputation with the villager decrease when captured in a bucket (Same effect as punching a villager)
# Only affects villagers, not zombie villagers or wandering traders
harm-reputation: false

# Should the server ask the client to download a resource pack when they join
resource-pack: true

# The below options are commented out so that it uses the right resourcepack version for the minecraft/plugin version by default
# If you want to override it/manually use an updated resourcepack you can uncomment and override them

# The URL to download the resource pack from
#resource-pack-url: "https://github.com/JustDoom/VillagerInABukkit/releases/download/Resourcepack-1.0.0/VillagerInABukkitPack.zip"
# The SHA-1 hash of the resource pack ZIP
#resource-pack-hash: "f2d4dd5bf8ee221234b738236099b2592c58b8e8"
# The ID for the resource pack. Please do not touch unless you know what you are doing
#resource-pack-id: "68a4b411-e409-4d89-b563-66049ba4914b"