name: VillagerInABukkit
main: com.imjustdoom.villagerinabucket.Main
version: 1.0.0
api-version: '1.21.4'
description: Plugin version of Villager In A Bucket
author: JustDoom
website: https://imjustdoom.com